export const CREATE_FLIGHT_ERROR = 'CREATE_FLIGHT_ERROR';
export const CREATE_FLIGHT_SUCCESS = 'CREATE_FLIGHT_SUCCESS';

export const REMOVE_FLIGHT_ERROR = 'REMOVE_FLIGHT_ERROR';
export const REMOVE_FLIGHT_SUCCESS = 'REMOVE_FLIGHT_SUCCESS';

export const UNDELETE_FLIGHT_ERROR = 'UNDELETE_FLIGHT_ERROR';

export const UPDATE_FLIGHT_ERROR = 'UPDATE_FLIGHT_ERROR';
export const UPDATE_FLIGHT_SUCCESS = 'UPDATE_FLIGHT_SUCCESS';

export const FILTER_FLIGHTS = 'FILTER_FLIGHTS';
export const LOAD_FLIGHTS_SUCCESS = 'LOAD_FLIGHTS_SUCCESS';
export const UNLOAD_FLIGHTS_SUCCESS = 'UNLOAD_FLIGHTS_SUCCESS';
