
export const Flight = {
	id: null,
	flight: null,
	date: false,
	launch_time_iso: null,
	landing_time_iso: null,
	duration_total_minutes: null,
	comments: null,
	// key:null,
	altitude_gain: null,
	landing_altitude: null,
	landing_zone: null,
	launch_altitude: null,
	launch_name: null,
	launch_orientation: null,
	max_altitude: null,
	site_name: null,
	total_airtime: null,
	vertical_drop: null,
	wind_direction: null,
	wind_speed: null,
	wing_name: null,
	xc_miles: null,
	updated_epoch: null,
};